### ISSUE TITLE
Bug: Cant cancel Mouse action when not assigning action in Primary.

### ISSUE THREAD

**Issue by MisteryMonster** [RamonUnch/AltSnap#183]
Checked `Without hotkey` when clicking the title bar and apply, Assign some action in `Mouse actions - title bar` mouse buttons, and set `Nothing` to the mouse buttons in `Primary`. Then when mouse click on title bar, it can't stop by releasing mouse clicks, have to pressing ESC to stop. Also `Move windows with a long left-click`.

BTW: since here we have `Move windows with a long left-click`, I wonder If we can custom action like Resize window, or adding long right-click with some actions? ( just explorer how to refine the action to compatible PowerToys FancyZones in just mouse clicks without touching keyboard!)

**Comment by RamonUnch** [comment]
> Checked `Without hotkey` when clicking the title bar and apply, Assign some action in `Mouse actions - title bar` mouse buttons, and set `Nothing` to the mouse buttons in `Primary`. Then when mouse click on title bar, it can't stop by releasing mouse clicks, have to pressing ESC to stop. Also `Move windows with a long left-click`.

Indeed, this is a problem.
It was not supposed to be possible to have a secondary action when you did not have a Priamry and the Titlebar action was added afterward. I will invistgate the problem.

> BTW: since here we have `Move windows with a long left-click`, I wonder If we can custom action like Resize window, or adding long right-click with some actions? ( just explorer how to refine the action to compatible PowerToys FancyZones in just mouse clicks without touching keyboard!)

Unfortunately AltSnap Has to generate a click with this option and if you do this with an other button than the left button then a menu will popup in many applications which make the option unusable.
I did several trials and the only functional answer I could find was the left click only.

**Comment by RamonUnch** [comment]
@MisteryMonster 
Have a try with this version, it should fix the problem you are describing.
Tell me if you still have more related problems.

Just extract and replace AltSnap.exe+Hooks.dll in your current install.
[AltSnap1.53test17_x64.zip](https://github.com/RamonUnch/AltSnap/files/8552378/AltSnap1.53test17_x64.zip)
[AltSnap1.53test17_i386.zip](https://github.com/RamonUnch/AltSnap/files/8552379/AltSnap1.53test17_i386.zip)

**Comment by MisteryMonster** [comment]
@RamonUnch Dam, I reply direct in the email but not shown...

The new one works great but new bugs created XD: 
1.When Primary Left mouse button assign to nothing, and "Move windows with a long left-click" is checked in the Activate with click menu, the left click will just broken!
2.If I click any mouse button after right click very quickly it will perform an double click.

**Comment by RamonUnch** [comment]
I see I t should not be hard to fix, however I will not be able to fix it before the end of next week, I will be in a disconnected place.

**Comment by RamonUnch** [comment]
Actually I could do it after two minutes (hopefully it works for real this time).
I will try on my side more to see if there are remaining problems.
This version should no longer "break" the left click
[AltSnap1.53test18_x64.zip](https://github.com/RamonUnch/AltSnap/files/8649155/AltSnap1.53test18_x64.zip)
[AltSnap1.53test18_i386.zip](https://github.com/RamonUnch/AltSnap/files/8649157/AltSnap1.53test18_i386.zip)

**Comment by MisteryMonster** [comment]
Just taking your times, the issue not solved (double click folder in Explorer and use mouse button 4 quickly, significant lagging and double clicked)

**Comment by RamonUnch** [comment]
I cannot reproduce this one, or maybe I do not understand the remaining issue?
There is big delay in my answer because my working mission ended to be twice longer than planned and now I have quite a few things going around, but I am still active.

Just to be sure, give me your .ini file (you can zip it and attach it in post), maybe i can reproduce with this last issue.

**Comment by MisteryMonster** [comment]
[AltSnap.zip](https://github.com/RamonUnch/AltSnap/files/8842795/AltSnap.zip)
I make a video when AltSnap on/off, hope it can help you to understand it.

https://user-images.githubusercontent.com/40703811/172120223-be135807-c565-4c62-b8a7-c2a1a8fcab28.mp4


https://user-images.githubusercontent.com/40703811/172120237-1600bf91-b776-4792-8cc8-dada1522e2a3.mp4

**Comment by RamonUnch** [comment]
I see on the video, but still cannot reproduce the bug with your .ini file (not using Win 10 however).
Does setting a primary action fixes it? In this case, you could set one up, it would not affect your config because all hotkeys are disabled.
I still need to fix that, but if it might be a solution for you in the meantime.

**Comment by MisteryMonster** [comment]
Yes, assign Primary action (button relative that problem) to something could fix that

**Comment by RamonUnch** [comment]
Just in case tell me if this one fixes it (I do not know if it will):
[AltSnap-1.53test24_i386.zip](https://github.com/RamonUnch/AltSnap/files/8843411/AltSnap-1.53test24_i386.zip)
[AltSnap-1.53test24_x64.zip](https://github.com/RamonUnch/AltSnap/files/8843413/AltSnap-1.53test24_x64.zip)

This build also include other non-related features and fixes.

**Comment by MisteryMonster** [comment]
This one not able to fix it XD.

**Comment by RamonUnch** [comment]
Well I could finally get access to a Win10 computer, reproduce your bug and, fix it:

[AltSnap1.53-test26_i386.zip](https://github.com/RamonUnch/AltSnap/files/8957825/AltSnap1.53-test26_i386.zip)
[AltSnap1.53-test26_x64.zip](https://github.com/RamonUnch/AltSnap/files/8957826/AltSnap1.53-test26_x64.zip)

It works for me on Win10 using your .ini file.

**Comment by MisteryMonster** [comment]
Yes, the problem solved! Thanks 😁
