### ISSUE TITLE
[suggestion] better snapping to edges animation

### ISSUE THREAD

**Issue by Alyaqdhans** [RamonUnch/AltSnap#563]
- try alt snapping an unresizable window like the "alt snap settings" and see what happens similar to  https://github.com/stefansundin/altdrag/issues/167

- is there a way to fix the janky snapping of WIndows 10 Explorer (and other apps, but mostly the explorer)? it just shows a lot of artifacts when trying to snap it with alt snap. Maybe you can somehow implement the smooth title bar snapping of windows to alt snap?

**Comment by Ichisich** [comment]
Point 1 is addressed by unchecking `Resize all windows` in the general tab.
Static windows then fall back to the action `move to next edge` instead of resizing.

Point 2 could be dependent on your performance settings. 
Windows explorer is notoriously unresponsive.

**Comment by Alyaqdhans** [comment]
Isn't it possible to make it look like windows snapping? When you touch an edge it won't snap immediately, it will show a preview like Windows does, and if released it will be there without showing the janky morphing.

Current state

https://github.com/user-attachments/assets/27d6b0c8-e69d-4ff7-9518-b90f54dfa3c4

Partial solution (as you said explorer is unresponsive and still shows some stuff, but it is still way better this way)
you can add a toggle for people who like it and who doesn't

https://github.com/user-attachments/assets/b50916d7-0f0a-4e10-a267-124326cea3ea

**Comment by RamonUnch** [comment]
This is duplicate of #106

If you want to see a preview of snapped windows, I suggest you set `FullWin=0` in the `[Performance]` section of the ini file. It will move a hollow rectangle and the window will only snap when releasing the click. You can also disable the "Show windows content while dradding" performance option in the Windows settings.
